#' Clean project
#' @param clean default = FALSE; if TRUE don't delete temp files generated by
#'   execution
#' @export
clean_project <- function(clean = FALSE, working_dir) {
  if (!is.null(working_dir)) {
    setwd(working_dir)
  }
  if (isTRUE(clean)){
    fs::dir_delete(fs::path(working_dir, "temp"))
    fs::dir_delete(fs::path(working_dir, "certs"))
    fs::dir_delete(fs::path(working_dir, "temp_repo"))
  }
}

