#' Clean project
#' @param clean default = FALSE; if TRUE don't delete temp files generated by
#'   execution
#' @export
clean_project <- function(clean = FALSE, prev_wd) {
  setwd(prev_wd)
  if (isTRUE(clean)){
    fs::dir_delete("temp")
    fs::dir_delete("certs")
    fs::dir_delete("temp_repo")
  }
}

